services:
  app:
    image: ${DOCKERHUB_USERNAME}/ai-chatbot:latest
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - POSTGRES_URL=${POSTGRES_URL}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - AUTH_SECRET=${AUTH_SECRET}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ai-chatbot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
