name: Database Migration
on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual triggers
  workflow_call:
    secrets:
      POSTGRES_URL:
        required: true

jobs:
  migrate:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run database migrations
        run: pnpm db:push
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}

      - name: Migration Successful
        run: echo "Database migration completed successfully."
